const data = [
  {
    id: "1",
    category: "java",
    video_link: "https://www.youtube.com/embed/hBh_CC5y8-s",
    titile: "Java Full Course | Java Tutorial for Beginners",
    auther: "Vinoth by Edureka",
    discription:
      "This Edureka Java Full Course will help you in understanding the various fundamentals of Java in detail with examples. ",
    language: "English",
  },
  {
    id: "2",
    category: "java",
    video_link: "https://www.youtube.com/embed/bSrm9RXwBaI",
    titile: "Java OOPs in One Shot | Object Oriented Programming",
    auther: "Shraddha by Apna College",
    discription:
      "This Video will help you in understanding the various fundamentals of Object Oriented Programming",
    language: "Hindi",
  },
  {
    id: "3",
    category: "java",
    video_link: "https://www.youtube.com/embed/UmnCZ7-9yDY",
    titile: "Basics of Java For Beginners ",
    auther: "Shraddha by Apna College",
    discription: "This Video will help you in understanding the Basics of Java",
    language: "Hindi",
  },
  {
    id: "4",
    category: "java",
    video_link: "https://www.youtube.com/embed/CFD9EFcNZTQ",
    titile: "Full Core Java Course In 11 Hours",
    auther: "Vikesh by Simplilearn",
    discription:
      "This video is based on Core Java Tutorial for Beginners. The Core Java Full Course in 10 Hours video will make sure all the major fundamentals are covered. ",
    language: "English",
  },
  {
    id: "5",
    category: "java",
    video_link:
      "https://www.youtube.com/embed/videoseries?list=PLfqMhTWNBTe3LtFWcvwpqTkUSlB32kJop",
    titile: "Beginners to Advans Full Java Coures Playlist [35 Videos]",
    auther: "Shraddha by Apna College",
    discription:
      "This Playlist is based on Core Java Tutorial for Beginners to Advans. The Core  and Advans Java Full Course Playlist will help you to Understand all the major fundamentals of java",
    language: "Hindi",
  },
  {
    id: "6",
    category: "java",
    video_link:
      "https://www.youtube.com/embed/videoseries?list=PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q",
    titile: "Beginners to Advans Full Java Coures Playlist [113 Videos]",
    auther: "Harry By Code with Harry",
    discription:
      "In this complete Core + Advance Java tutorial for beginners in hindi, we will see complete java topics covered in hindi. This java complete tutorial will cover topics like Downloading Java, Installation of Java, java JVM, java inheritance, java inheritance & polymorphism and other complete java tutorial topics will be covered.",
    language: "Hindi",
  },
  {
    id: "7",
    category: "java",
    video_link: "https://www.youtube.com/embed/aQatrXw0njs",
    titile: "Learn Basics of Java in One video for Beginners ",
    auther: "Anuj By Anuj Bhaiya",
    discription:
      "This Video Help You to Learn Basic and Rivise of Java in Just One Hour ",
    language: "Hindi",
  },
  {
    id: "8",
    category: "java",
    video_link: "https://www.youtube.com/embed/OWCao3Ul6n4",
    titile:
      "Data Structure and Algorithms in JAVA | Full Course on Data Structure",
    auther: "By Great Learning",
    discription:
      "In this course, we are going to discuss Data Structures and Algorithms using Java Programming. The data structure is a way to store and organize data so that it can be used efficiently. It is a set of concepts that we can use in any programming language to structure the data in the memory. Data structures are widely used in almost every aspect of computer science  Some examples of Data structures that we are going to cover in this course are arrays, linked lists, stack, queue, Binary Tree, Binary Search Tree, Graphs, etc.",
    language: "English",
  },
  {
    id: "9",
    category: "java",
    video_link: "https://www.youtube.com/embed/videoseries?list=PLUcsbZa0qzu3yNzzAxgvSgRobdUUJvz7p",
    titile: "DSA One Course| The Complate Data Structure and Algorithms Course [100` Videos]",
    auther: "Anuj By Anuj Bhaiya",
    discription: "In this course, we are going to discuss all the Data Structures and Algorithms Concepts Step by Step using Java Programming. Some examples of Data structures that we are going to cover in this course are arrays, linked lists, stack, queue, Binary Tree, Binary Search Tree, Graphs, etc.",
    language: "Hindi",
  },
  {
    id: "10",
    category: "JavaScript",
    video_link: "https://www.youtube.com/embed/videoseries?list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ",
    titile: "Interview Peperation + Complate Data Structure and Algorithms Course [46 Videos]",
    auther: "Kunal Kushwaha ",
    discription: "Here I share about my approaches that led me to clear interviews of top tier companies like Google off-campus, & get all the amazing opportunities. Get interview-ready with this course that has no prerequisites and is designed to make you an expert in solving easy to hard LeetCode problems with ease.",
    language: "English",
  },
  {
    id: "11",
    category: "JavaScript",
    video_link: "https://www.youtube.com/embed/hCrO_cR7kno",
    titile: "Data Structures and Algorithms Full Course for Beginners",
    auther: "WsCube Tech",
    discription: "This video is a one-stop solution if you are looking for a data structures and algorithm tutorial. It explains the data structures and algorithms which will take you from beginner to expert in one go.We will explain data structures and algorithms from start to finish.",
    language: "Hindi",
  },
  {
    id: "12",
    category: "javaScript",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "13",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "14",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "15",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "16",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "17",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "18",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "19",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "20",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "21",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "22",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "23",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "24",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "25",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "26",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "27",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "28",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "29",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "30",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "31",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "32",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "33",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "34",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "35",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "36",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "37",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "38",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "39",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "40",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "41",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "42",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "43",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "44",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "45",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "46",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "47",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "48",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "49",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "50",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
  {
    id: "51",
    category: "java",
    video_link: "",
    titile: "",
    auther: "",
    discription: "",
    language: "",
  },
];

export default data;
